### ISSUE TITLE
Organization Schema

### ISSUE THREAD

**Issue by cbode** [DendraScience/dendra-json-schema#1]
Organizations need several more fields:
description
full_name (name is moved to full_name)
slug
name becomes the shorter common name

**Comment by jscottsf** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Recurring: Review GitHub issues](https://trello.com/c/wW7jeq8H/228-recurring-review-github-issues)

**Comment by jscottsf** [comment]
Resolved by commit b7493067454ef733eeb65c1da66a70233a52ca22.
