### ISSUE TITLE
GEO JSON - MultiPolygon

### ISSUE THREAD

**Issue by cbode** [DendraScience/dendra-json-schema#2]
Places have the ability to use either lat/long/elevation or a geo json object.   Currently Polygon is allowed, but MultiPolygon is not.  It should be added as it is common for cases where islands are part of a boundary or inholdings in legal properties cause discontinuities.

**Comment by jscottsf** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Recurring: Review GitHub issues](https://trello.com/c/wW7jeq8H/228-recurring-review-github-issues)
